<template>
  <main class="saas-workbench page-grid"><PageToolbar title="数据治理" description="处理导出、删除和法律冻结审批，查看各存储执行进度与审计证据。"><template #actions><button class="ghost-btn compact-btn" :disabled="loading" @click="load">刷新</button></template></PageToolbar>
    <ResourceContextRail label="治理范围" name="企业业务数据" :state="loading ? '加载中' : '可治理'" hint="请求需审批，部分失败可按阶段重试" mark="G" />
    <section class="saas-status-strip"><div class="saas-status-item"><small>待审批</small><strong>{{ count('PENDING_APPROVAL') }} 项</strong></div><div class="saas-status-item"><small>后台处理中</small><strong>{{ count('RUNNING') }} 项</strong></div><div class="saas-status-item"><small>部分失败</small><strong>{{ count('PARTIAL_FAILED') }} 项</strong></div><div class="saas-status-item"><small>保留策略</small><strong>{{ policies.length }} 项</strong></div></section>
    <section class="saas-work-area"><nav class="saas-task-nav"><button :class="{active:tab==='requests'}" @click="tab='requests'">治理请求</button><button :class="{active:tab==='create'}" @click="tab='create'">新建请求</button><button :class="{active:tab==='retention'}" @click="tab='retention'">保留策略</button><button :class="{active:tab==='hold'}" @click="tab='hold'">法律冻结</button></nav><div class="saas-pane">
      <PageState v-if="error" type="error" title="数据治理加载失败" :message="error" action-label="重新加载" @action="load" /><PageState v-else-if="loading" type="loading" message="正在从服务端恢复治理进度..." />
      <template v-else-if="tab==='requests'"><div class="saas-pane-head"><div><h2>持久化治理请求</h2><p>删除任务只有全部存储完成后才显示成功；失败阶段可单独重试。</p></div></div><div v-if="!requests.length" class="saas-state">当前没有治理请求。</div><div v-else class="saas-table-wrap"><table class="saas-table"><thead><tr><th>类型</th><th>状态</th><th>范围摘要</th><th>主库</th><th>向量索引</th><th>对象存储</th><th>操作</th></tr></thead><tbody><tr v-for="item in requests" :key="item.id"><td>{{ typeLabel(item.requestType) }}</td><td><span class="saas-tag" :class="statusClass(item.requestStatus)">{{ statusLabel(item.requestStatus) }}</span></td><td>{{ item.scopeSummary||'已选择业务范围' }}</td><td>{{ stage(item,'DATABASE') }}</td><td>{{ stage(item,'QDRANT') }}</td><td>{{ stage(item,'OBJECT_STORAGE') }}</td><td><div class="saas-actions"><button v-if="item.requestStatus==='PENDING_APPROVAL'" class="ghost-btn compact-btn" @click="approve(item)">批准</button><button v-if="item.requestStatus==='APPROVED'" class="primary-btn compact-btn" @click="execute(item)">开始执行</button><button v-if="item.requestStatus==='PARTIAL_FAILED'" class="ghost-btn compact-btn" @click="retry(item)">重试失败阶段</button><button class="ghost-btn compact-btn" @click="showEvidence(item)">查看证据</button></div></td></tr></tbody></table></div><div v-if="evidence.length" class="saas-table-wrap"><table class="saas-table"><thead><tr><th>存储</th><th>结果</th><th>处理数量</th><th>证据摘要</th></tr></thead><tbody><tr v-for="item in evidence" :key="item.id"><td>{{ storeLabel(item.storeType) }}</td><td>{{ statusLabel(item.executionStatus) }}</td><td>{{ item.affectedCount||0 }}</td><td>{{ item.evidenceHash||item.safeSummary||'已记录，不包含数据正文' }}</td></tr></tbody></table></div></template>
      <template v-else-if="tab==='create'"><div class="saas-pane-head"><div><h2>新建治理请求</h2><p>请求提交后进入审批，服务端会保存范围和执行证据。</p></div></div><div class="saas-form-grid"><div class="saas-field"><label>请求类型</label><select v-model="form.type"><option value="EXPORT">数据导出</option><option value="DELETE">数据删除</option></select></div><div class="saas-field"><label>数据类别</label><select v-model="form.scope.dataCategory"><option value="ALL">全部业务数据</option><option value="CONVERSATION">对话记录</option><option value="DOCUMENT">知识文档</option><option value="RUN">运行记录</option><option value="AUDIT">审计记录</option></select></div><div class="saas-field wide"><label>业务应用（可选）</label><ResourceSelect v-model="form.scope.applicationId" :options="applicationOptions" resource-label="业务应用" placeholder="全部应用" /></div><div class="saas-field"><label>开始日期（可选）</label><input v-model="form.scope.from" type="date" /></div><div class="saas-field"><label>结束日期（可选）</label><input v-model="form.scope.to" type="date" /></div></div><div class="saas-actions"><button class="primary-btn" :disabled="submitting" @click="create">提交审批</button></div></template>
      <template v-else-if="tab==='retention'"><div class="saas-pane-head"><div><h2>数据保留策略</h2><p>按数据类别执行版本化保留，活动法律冻结优先于自动清理。</p></div></div><div v-if="!policies.length" class="saas-state">尚未配置保留策略。</div><div v-else class="saas-table-wrap"><table class="saas-table"><thead><tr><th>数据类别</th><th>保留天数</th><th>法律依据</th><th>版本</th><th>状态</th></tr></thead><tbody><tr v-for="item in policies" :key="item.id"><td>{{ item.dataCategory }}</td><td>{{ item.retentionDays }} 天</td><td>{{ item.legalBasis||'未填写' }}</td><td>第 {{ item.versionNo }} 版</td><td>{{ statusLabel(item.status) }}</td></tr></tbody></table></div></template>
      <template v-else><div class="saas-pane-head"><div><h2>创建法律冻结</h2><p>冻结范围内的数据不会被普通删除或到期清理。</p></div></div><div class="saas-form-grid"><div class="saas-field"><label>冻结编号</label><input v-model.trim="hold.holdCode" /></div><div class="saas-field"><label>原因摘要</label><input v-model.trim="hold.reason" /></div><div class="saas-field"><label>冻结数据类别</label><select v-model="hold.scope.dataCategory"><option value="ALL">全部业务数据</option><option value="CONVERSATION">对话记录</option><option value="DOCUMENT">知识文档</option><option value="RUN">运行记录</option><option value="AUDIT">审计记录</option></select></div><div class="saas-field"><label>业务应用（可选）</label><ResourceSelect v-model="hold.scope.applicationId" :options="applicationOptions" resource-label="业务应用" placeholder="全部应用" /></div><div class="saas-field"><label>开始日期（可选）</label><input v-model="hold.scope.from" type="date" /></div><div class="saas-field"><label>结束日期（可选）</label><input v-model="hold.scope.to" type="date" /></div></div><div class="saas-actions"><button class="primary-btn" :disabled="submitting" @click="createHold">创建冻结</button></div></template>
    </div></section>
  </main>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'
import PageToolbar from '../components/PageToolbar.vue'
import PageState from '../components/PageState.vue'
import ResourceContextRail from '../components/ResourceContextRail.vue'
import ResourceSelect from '../components/structured/ResourceSelect.vue'
import { fetchRuntimeApplications } from '../api/runtime'
import { approveGovernanceRequest, createGovernanceRequest, createLegalHold, executeGovernanceRequest, fetchGovernanceEvidence, fetchGovernanceRequests, fetchRetentionPolicies, retryGovernanceRequest } from '../api/saas'
import { notify } from '../utils/feedback'
import { useMutationState } from '../composables/useMutationState.js'
const tab=ref('requests'),loading=ref(false),submitting=ref(false),error=ref(''),requests=ref([]),policies=ref([]),evidence=ref([]),applicationOptions=ref([])
const emptyScope=()=>({dataCategory:'ALL',applicationId:'',from:'',to:''})
const form=reactive({type:'EXPORT',scope:emptyScope()}),hold=reactive({holdCode:'',scope:emptyScope(),reason:''})
const mutation = useMutationState()
const count=status=>requests.value.filter(i=>i.requestStatus===status).length
const typeLabel=v=>v==='EXPORT'?'数据导出':v==='DELETE'?'数据删除':'治理请求'
const statusLabel=v=>({PENDING_APPROVAL:'待审批',APPROVED:'已批准',RUNNING:'处理中',SUCCEEDED:'已完成',COMPLETED:'已完成',PARTIAL_FAILED:'部分失败',FAILED:'失败',ACTIVE:'生效中'}[v]||'未知状态')
const statusClass=v=>['FAILED','PARTIAL_FAILED'].includes(v)?'bad':['PENDING_APPROVAL','RUNNING'].includes(v)?'warn':''
const storeLabel=v=>({DATABASE:'主数据库',QDRANT:'向量索引',OBJECT_STORAGE:'对象存储',CACHE:'缓存',TASK_QUEUE:'异步任务'}[v]||'其他存储')
const stage=(item,store)=>item.stageResults?.find(i=>i.storeType===store)?.executionStatus?statusLabel(item.stageResults.find(i=>i.storeType===store).executionStatus):'等待执行'
async function load(){loading.value=true;error.value='';try{const [a,b,apps]=await Promise.all([fetchGovernanceRequests(),fetchRetentionPolicies(),fetchRuntimeApplications()]);requests.value=a.data||[];policies.value=b.data||[];applicationOptions.value=(apps.data||[]).map(item=>({value:String(item.id),label:item.name||item.appName||'未命名应用',status:item.status==='ACTIVE'?'可用':''}))}catch(e){error.value=e.message||'治理数据加载失败，请检查合规权限。'}finally{loading.value=false}}
async function action(key,fn,message){submitting.value=true;error.value='';try{await mutation.run(key,fn,load);notify(message,'success')}catch(e){error.value=e.message||'操作未完成，请稍后重试。'}finally{submitting.value=false}}
const scopePayload=scope=>({dataCategory:scope.dataCategory,applicationId:scope.applicationId?Number(scope.applicationId):null,from:scope.from||null,to:scope.to||null})
const create=()=>action('governance-create',()=>createGovernanceRequest(form.type,{scope:scopePayload(form.scope)}),'治理请求已提交')
const approve=item=>action(`governance-approve-${item.id}`,()=>approveGovernanceRequest(item.id),'治理请求已批准')
const execute=item=>action(`governance-execute-${item.id}`,()=>executeGovernanceRequest(item.id),'后台任务已启动')
const retry=item=>action(`governance-retry-${item.id}`,()=>retryGovernanceRequest(item.id),'失败阶段已重新排队')
const createHold=()=>action('governance-hold',()=>createLegalHold({holdCode:hold.holdCode,reason:hold.reason,scope:scopePayload(hold.scope)}),'法律冻结已创建')
async function showEvidence(item){try{const res=await fetchGovernanceEvidence(item.id);evidence.value=res.data||[]}catch(e){error.value=e.message}}
onMounted(load)
</script>
