<template>
  <div class="page-grid"><section class="section-card"><div class="section-header"><div><h3>模型价格规则</h3><p class="section-description">维护平台统一 Token 价格，价格会影响后续真实调用成本统计。</p></div><button class="primary-btn" @click="openCreate">新增价格规则</button></div>
    <p v-if="message" :class="messageType">{{ message }}</p><div v-if="prices.length === 0" class="empty-state">暂无模型价格规则。</div>
    <table v-else class="table-card"><thead><tr><th>供应商</th><th>模型名称</th><th>输入价 / 1K</th><th>输出价 / 1K</th><th>生效时间</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in prices" :key="item.id"><td>{{ item.provider }}</td><td>{{ item.modelKey }}</td><td>{{ item.inputPricePer1k }}</td><td>{{ item.outputPricePer1k }}</td><td>{{ formatTime(item.effectiveFrom) }}</td><td>{{ item.status }}</td><td><button class="ghost-btn compact-btn" @click="edit(item)">编辑</button><button class="danger-link" @click="remove(item.id)">删除</button></td></tr></tbody></table>
  </section><div v-if="dialog" class="modal-overlay"><section class="modal-card"><h3>{{ form.id ? '编辑' : '新增' }}价格规则</h3><label>模型连接<select v-model="selectedModel" class="text-input"><option value="">请选择模型中心中的模型</option><option v-for="model in modelOptions" :key="model.id" :value="model.provider + '|' + model.modelKey">{{ model.modelName }}（{{ model.provider }} / {{ model.modelKey }}）</option></select></label><small class="field-help">供应商和模型名称来自模型中心，避免价格规则绑定到不存在的模型。</small><label>输入价格 / 1K Token<input v-model.number="form.inputPricePer1k" type="number" min="0" step="0.000001" class="text-input" autocomplete="off" spellcheck="false" /></label><label>输出价格 / 1K Token<input v-model.number="form.outputPricePer1k" type="number" min="0" step="0.000001" class="text-input" autocomplete="off" spellcheck="false" /></label><div class="modal-actions"><button class="ghost-btn" @click="dialog = false">取消</button><button class="primary-btn" :disabled="!form.provider || !form.modelKey" @click="save">保存</button></div></section></div></div>
</template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'; import PageToolbar from '../components/PageToolbar.vue'; import http from '../api/http'; import { confirmAction } from '../utils/feedback'
const prices = ref([]); const modelOptions = ref([]); const dialog = ref(false); const message = ref(''); const messageType = ref('success-text'); const form = reactive({ id: null, provider: '', modelKey: '', inputPricePer1k: 0, outputPricePer1k: 0, status: 'ACTIVE' })
const selectedModel = computed({ get: () => form.provider && form.modelKey ? `${form.provider}|${form.modelKey}` : '', set: value => { const separator = value.indexOf('|'); form.provider = separator < 0 ? '' : value.slice(0, separator); form.modelKey = separator < 0 ? '' : value.slice(separator + 1) } })
const formatTime = value => value ? new Date(value).toLocaleString('zh-CN') : '立即生效'
const load = async () => { try { const [priceResponse, modelResponse] = await Promise.all([http.get('/system/model-prices'), http.get('/system/models')]); prices.value = priceResponse.data || []; message.value = ''; modelOptions.value = (modelResponse.data || []).filter(item => item.status === 'ACTIVE') } catch (error) { messageType.value = 'error-text'; message.value = error?.message || '读取模型价格规则失败，请检查后端服务和数据库配置。' } }
const openCreate = () => { Object.assign(form, { id: null, provider: '', modelKey: '', inputPricePer1k: 0, outputPricePer1k: 0, status: 'ACTIVE' }); dialog.value = true }
const edit = item => { Object.assign(form, item); dialog.value = true }
const save = async () => { try { const payload = { provider: form.provider, modelKey: form.modelKey, inputPricePer1k: form.inputPricePer1k, outputPricePer1k: form.outputPricePer1k, status: form.status }; if (form.id) await http.put(`/system/model-prices/${form.id}`, payload); else await http.post('/system/model-prices', payload); dialog.value = false; messageType.value = 'success-text'; message.value = '模型价格规则已保存。'; await load() } catch (error) { messageType.value = 'error-text'; message.value = error?.message || '保存模型价格规则失败，请检查后端服务和数据库配置。' } }
const remove = async id => { if (!await confirmAction({ title: '删除价格规则', message: '删除后，新的模型调用将无法使用这条价格配置。' })) return; try { await http.delete(`/system/model-prices/${id}`); await load() } catch (error) { messageType.value = 'error-text'; message.value = error?.message || '删除模型价格规则失败，请检查后端服务和数据库配置。' } }
onMounted(load)
</script>
<style scoped>.section-header { display:flex; justify-content:space-between; gap:16px; align-items:flex-start; }.section-card label { display:grid; gap:7px; margin-top:12px; color:var(--text-secondary); font-size:13px; }.modal-card { width:min(520px, calc(100vw - 32px)); }.modal-actions { display:flex; justify-content:flex-end; gap:10px; margin-top:18px; }.success-text { color:#087443; }.error-text { color:#b42318; }.danger-link { border:0; background:transparent; color:#b42318; cursor:pointer; margin-left:8px; }</style>
